services:
  db:
    image: postgres:16-alpine
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: 2831742dfcz
      POSTGRES_DB: cspap
    volumes:
      - pgdata:/var/lib/postgresql/data
    healthcheck:
      test: ['CMD-SHELL', 'pg_isready -U postgres -d cspap']
      interval: 5s
      timeout: 3s
      retries: 20
    restart: unless-stopped

  backend:
    build: ./backend
    env_file:
      - ./backend/.env
    environment:
      NODE_ENV: production
      UPLOAD_DIR: /app/uploads
    volumes:
      - /srv/storage/uploads:/app/uploads
    depends_on:
      db:
        condition: service_healthy
    expose:
      - '3000'
    restart: unless-stopped

  frontend:
    build:
      context: ./frontend
      dockerfile: ./Dockerfile
    env_file:
      - ./frontend/.env # только VITE_* переменные
    expose:
      - '80'
    depends_on:
      - backend
    restart: unless-stopped

volumes:
  pgdata:
